const webDevSpecial = [
  'REACT',
  'JAVASCRIPT',
  'NODE',
  'EXPRESS',
  'REDUX',
  'VUE',
  'GATSBY',
  'SASS',
  'AWS',
  'NETLIFY',
  'DIGITALOCEAN',
  'GIT',
  'PHOTOSHOP',
  'ILUSTRATOR',
  'ADOBEXD',
];

const skillTable = {
  FULLSTACK: { isActive: false, special: null },
  TI: { isActive: false, special: null },
  REACT: { isActive: false, iconPath: '', special: null },
  JAVASCRIPT: { isActive: false, iconPath: '', special: null },
  NODE: { isActive: false, iconPath: '', special: null },
  EXPRESS: { isActive: false, iconPath: '', special: null },
  REDUX: { isActive: false, iconPath: '', special: null },
  VUE: { isActive: false, iconPath: '', special: null },
  GATSBY: { isActive: false, iconPath: '', special: null },
  SASS: { isActive: false, iconPath: '', special: null },
  AWS: { isActive: false, iconPath: '', special: null },
  NETLIFY: { isActive: false, iconPath: '', special: null },
  GIT: { isActive: false, iconPath: '', special: null },
  DIGITALOCEAN: { isActive: false, iconPath: '', special: null },
  PHOTOSHOP: { isActive: false, iconPath: '', special: null },
  ILUSTRATOR: { isActive: false, iconPath: '', special: null },
  ADOBEXD: { isActive: false, iconPath: '', special: null },
  WEBDEV: { isActive: false, iconPath: '', special: [...webDevSpecial] },
  PYTHON: { isActive: false, iconPath: '', special: null },
  'C#': { isActive: false, iconPath: '', special: null },
  DOCKER: { isActive: false, iconPath: '', special: null },
  WEBSERVICES: { isActive: false, iconPath: '', special: null },
  TDD: { isActive: false, iconPath: '', special: null },
  LINKEDIN: { isActive: false, iconPath: '', special: null },
  TWITTER: { isActive: false, iconPath: '', special: null },
  GITHUB: { isActive: false, iconPath: '', special: null },
  'DATA SCIENCE': { isActive: false, iconPath: '', special: null },
};
export default skillTable;
