const skillTable = {
  FULLSTACK: () => console.log('Full Stack'),
  TI: () => console.log('ti'),
  REACT: { isActive: false, iconPath: '' },
  JAVASCRIPT: { isActive: false, iconPath: '' },
  NODE: { isActive: false, iconPath: '' },
  EXPRESS: { isActive: false, iconPath: '' },
  REDUX: { isActive: false, iconPath: '' },
  VUE: { isActive: false, iconPath: '' },
  GATSBY: { isActive: false, iconPath: '' },
  SASS: { isActive: false, iconPath: '' },
  AWS: { isActive: false, iconPath: '' },
  NETLIFY: { isActive: false, iconPath: '' },
  DIGITALOCEAN: { isActive: false, iconPath: '' },
  GIT: { isActive: false, iconPath: '' },
  PHOTOSHOP: { isActive: false, iconPath: '' },
  ILUSTRATOR: { isActive: false, iconPath: '' },
  ADOBEXD: { isActive: false, iconPath: '' },
  WEBDEV: { isActive: false, iconPath: '' },
  PYTHON: { isActive: false, iconPath: '' },
  'C#': { isActive: false, iconPath: '' },
  DOCKER: { isActive: false, iconPath: '' },
  WEBSERVICES: { isActive: false, iconPath: '' },
  TDD: { isActive: false, iconPath: '' },
  LINKEDIN: { isActive: false, iconPath: '' },
  TWITTER: { isActive: false, iconPath: '' },
  GITHUB: { isActive: false, iconPath: '' },
  'DATA SCIENCE': { isActive: false, iconPath: '' },
};
export default skillTable;
